### PR TITLE
Big refactor to match arduino logic separation

### PR DESCRIPTION
**Pull request by ladyada**
this also made it possible to add more displays, now has 2.7" tricolor support!

### CODE REVIEW

**Comment by deshipu** [comment]
Tested with the https://www.adafruit.com/product/3625 and a Feather M0 Basic on the CP4.0beta6 with the simpletest:
IMG_20190331_224516

**Comment by anecdata** [comment]
Tested with Feather M4 on the CP4.0beta6 with simpletest modified:
D9 & D10 are switched, and srcs = None, rst = None, and busy = None
and updated (yesterday) framebuf from ladyada/Adafruit_CircuitPython_framebuf
Screen Shot 2019-03-31 at 5 52 44 PM

**Comment by ladyada** [comment]
yah almost done!

**Comment by makermelissa** [comment]
Want me to bump?

**Pull request merged**
